# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bc6e0434bb64e319e575366b0a1bc5ea431f9e602c93820319f0394bf1bd9344542cca604cb10326061b54500eae6b5afe08ffbb999aa877fda7b16e4b0fb7c

test:
  secret_key_base: 1922e2742a4d8a48313373ea78297251b28a5a58aeaef5737563bd44f02c2781d71eb4f7e5a5463b6b802ba065f22e30a09ad0ce95d83f7eb395b620a22c89d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
